version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      [user-service, matching-service, communication-service, collaboration-service, question-service]

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - 8000:8000
    depends_on:
      [mongo-user, redis]

  mongo-user:
    container_name: mongo-user
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-user-volume:/data/db

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data

  matching-service:
    container_name: matching-service
    build:
      context: ./matching-service
    ports:
      - 8001:8001

  communication-service:
    container_name: communication-service
    build:
      context: ./communication-service
    ports:
      - 8002:8002
    depends_on:
      - mongo-comm

  mongo-comm:
    container_name: mongo-comm
    image: mongo
    ports:
      - 27019:27017
    volumes:
      - mongo-comm-volume:/data/db

  collaboration-service:
    container_name: collaboration-service
    build:
      context: ./collaboration-service
    ports:
      - 8003:8003

  question-service:
    container_name: question-service
    build:
      context: ./question-service
    ports:
      - 8004:8004
    depends_on:
      - mongo-question

  mongo-question:
    container_name: mongo-question
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongo-question-volume:/data/db

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - 8080:8080
    restart: always
    depends_on:
      [frontend, user-service, matching-service, communication-service, collaboration-service, question-service]

volumes:
  mongo-user-volume:
  mongo-comm-volume:
  mongo-question-volume:
  redis-volume:
