apiVersion: v1
kind: Service
metadata:
  # Define the Service name
  name: collab-service
  labels:
    app: collab
spec:
  # Scans for Pods that match its selector
  selector:
    app: collab
  # Exposes the Service on a cluster-internal IP. 
  # Hence, this Service is only reachable from within the cluster. 
  type: ClusterIP
  ports:
    - name: collab-http
      port: 8003
      protocol: TCP
      targetPort: collab-http
