apiVersion: v1
kind: Service
metadata:
  # Define the Service name
  name: auth-service
  labels:
    app: auth
spec:
  # Scans for Pods that match its selector
  selector:
    app: auth
  # Exposes the Service on a cluster-internal IP. 
  # Hence, this Service is only reachable from within the cluster. 
  type: ClusterIP
  ports:
    - name: auth-http
      port: 8005
      protocol: TCP
      targetPort: auth-http
