apiVersion: v1
kind: Service
metadata:
  # Define the Service name
  name: matching-service
  labels:
    app: matching
spec:
  # Scans for Pods that match its selector
  selector:
    app: matching
  # Exposes the Service on a cluster-internal IP. 
  # Hence, this Service is only reachable from within the cluster. 
  type: ClusterIP
  ports:
    - name: matching-http
      port: 8001
      protocol: TCP
      targetPort: matching-http
