apiVersion: apps/v1
kind: Deployment
metadata:
  # Define the Deployment name
  name: user-deployment
  labels:
    app: user
spec:
  # Specify the number of desired Pods
  replicas: 1
  # Define how the Deployment finds which Pods to manage
  selector:
    matchLabels:
      app: user
  # Define template for Pods
  template:
    metadata:
      labels:
        app: user
    spec:
      # Container details
      containers:
        - name: user-deployment
          image: gcr.io/cs3219-g28-peerprep/user:latest
          ports:
            - name: user-http
              containerPort: 8000
          resources:
            limits:
              cpu: 40m
              memory: 100Mi
          env:
            - name: ENV
              value: PROD
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: FRONTEND_URL
            - name: DB_CLOUD_URI
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: DB_CLOUD_URI
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: JWT_SECRET_KEY
            - name: REDIS_CLOUD_HOST
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: REDIS_CLOUD_HOST
            - name: REDIS_CLOUD_PORT
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: REDIS_CLOUD_PORT
            - name: REDIS_CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: REDIS_CLOUD_PASSWORD
