apiVersion: v1
kind: Service
metadata:
  # Define the Service name
  name: question-service
  labels:
    app: question
spec:
  # Scans for Pods that match its selector
  selector:
    app: question
  # Exposes the Service on a cluster-internal IP. 
  # Hence, this Service is only reachable from within the cluster. 
  type: ClusterIP
  ports:
    - name: question-http
      port: 8004
      protocol: TCP
      targetPort: question-http
